### PR TITLE
Touchscreen view

### PR DESCRIPTION
**Pull request by g3rg**
Basic WIP mode for touchscreen usability. Wraps items in a Bootstrap Carousel, to allow swiping between sections.

Currently has the 'FactionSpecificData' page as one page, but might be better to divide that up, but need some more time to work on that.

### CODE REVIEW

**Comment by Floppy** [comment]
Nice! I'll have a go here later on! I've converted it to a draft to remind me it's not ready for merge yet. If that's wrong, feel free to change it back :)

**Comment by g3rg** [comment]
> Nice! I'll have a go here later on! I've converted it to a draft to remind me it's not ready for merge yet. If that's wrong, feel free to change it back :)

I'm happy for it to be merged, as long as it fits your usability etc review, or wait for further work. I have my own deployment that I'm using for games with it so no rush for me personally!.

I do want to look at the "FactionSpecificData" pages, however I may not get a chance till the weekend.

**Comment by Floppy** [comment]
OK, cool, I'll change it back if it's all working, then review and merge when I've given it a test.

**Comment by Floppy** [comment]
So sorry, I forgot to review this! I'll try to do it soon!

**Review by Floppy — APPROVED** [review]

**Pull request merged**
