### PR TITLE
Shadowvaults

### PR DESCRIPTION
**Pull request by g3rg**
Ploys and Tac Ops added for Shadowvaults team, waiting on Battlescribe to test / see if Abilities need to be added.

### CODE REVIEW

**Comment by Floppy** [comment]
@gr3g I've fixed the build errors, is this ready to go in?

**Comment by Floppy** [comment]
@g3rg  I've fixed the build errors, is this ready to go in?

**Comment by g3rg** [comment]
@Floppy Last I checked BattleScribe hasn't been updated yet, so unfortunately, not ready to go. There may also be more faction specific things to add depending on how much goes into the Battlescribe data for them. Cheers for fixing the build errors, I was pretty sure it wasn't the code!

**Comment by g3rg** [comment]
@Floppy I think this is good to go. I've opted to just do a link to Wahapedia for the Hierotek Circle Reanimation protocol, rather than enter it all within the app. I think we discussed previously that the precedence of should be 1) Source from Battlescribe file, 2) Source/link to Wahapedia 3) Enter into DataSlate source files.

**Comment by Floppy** [comment]
Sounds good to me!

**Pull request merged**
